project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false
website:
  title: "Artur Pericles L. Monteiro"
  site-url: "/"
  # favicon: media/api-favicon.png
  navbar:
    title: ARTUR PERICLES L. MONTEIRO
    right:
      - href: about/
        text: About
      - href: publications/
        text: Publications
      - href: teaching/
        text: Teaching
      - href: talks/
        text: Talks              
format: 
  html:
    theme:
      light:
        # - cosmo
        - assets/theme.scss
        # - assets/silvia/colors-light.scss
        - assets/fonts.scss      
    pagetitle: '{{< meta title >}}'
    lightbox: true


